FROM rust:1.84-bookworm AS builder

ARG commitHash
ENV MEMPOOL_COMMIT_HASH=${commitHash}

WORKDIR /build

RUN apt-get update && \
    apt-get install -y curl ca-certificates && \
    curl -fsSL https://deb.nodesource.com/setup_24.x | bash - && \
    apt-get install -y nodejs=24.13.0-1nodesource1 build-essential python3 pkg-config && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY . .

ENV PATH="/usr/local/cargo/bin:$PATH"

#COPY --from=backend . .
#COPY --from=rustgbt . ../rust/
ENV FD=/build/rust-gbt

WORKDIR /build/backend
RUN npm install --omit=dev --omit=optional
RUN echo "=== build dir ===" \
 && ls -la /build \
 && echo "=== rust-gbt dir ===" \
 && ls -la /build/backend/rust-gbt || true

# Fix für rust-gbt Ziel
RUN mv /build/rust-gbt /build/backend/rust-gbt

RUN npm run package
RUN echo "=== BUILD TREE ===" && ls -la /build
RUN echo "=== BACKEND TREE ===" && ls -la /build/backend

FROM rust:1.84-bookworm AS runtime

RUN apt-get update && \
    apt-get install -y curl ca-certificates && \
    curl -fsSL https://deb.nodesource.com/setup_24.x | bash - && \
    apt-get install -y nodejs=24.13.0-1nodesource1 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /backend

RUN chown 1000:1000 ./
COPY --from=builder --chown=1000:1000 /build/backend/package ./package/
COPY --from=builder --chown=1000:1000 /build/backend/rust-gbt ./rust-gbt/
COPY --from=builder --chown=1000:1000 /build/backend/node_modules ./node_modules/
COPY --from=builder --chown=1000:1000 /build/backend/mempool-config.json ./mempool-config.json
COPY --from=builder --chown=1000:1000 /build/backend/start.sh ./start.sh
COPY --from=builder --chown=1000:1000 /build/backend/wait-for-it.sh ./wait-for-it.sh

#COPY --from=builder --chown=1000:1000 /build/package ./package/
#COPY --from=builder --chown=1000:1000 /build/GeoIP ./GeoIP/
#COPY --from=builder --chown=1000:1000 /build/mempool-config.json /build/start.sh /build/wait-for-it.sh ./

USER 1000

EXPOSE 8999

CMD ["/backend/start.sh"]
