# Basis für neues Image
FROM node:24.13-bookworm-slim AS builder

ARG commitHash
ENV DOCKER_COMMIT_HASH=${commitHash}
ENV CYPRESS_INSTALL_BINARY=0

WORKDIR /build
COPY . .
COPY ./docker/frontend/ .
WORKDIR /build/frontend
RUN apt-get update
RUN apt-get install -y build-essential rsync
RUN cp frontend/mempool-frontend-config.sample.json mempool-frontend-config.json

# Das obige Image wird um ziemlich viel Bibliotheken und npm build erweitert
# zum Beispiel entstehen hier die node_modules

RUN npm install --omit=dev --omit=optional	

# mein neuer Mempool wird gebaut

RUN npm run build				

# Jetzt wird ein neues image erstellt (das Finale), auf Basis des folgenden Images (nginx). Aus dem vorgergehendem
# Bild wird lediglich alles fertige dann rüberkopiert
FROM nginx:1.27.0-alpine			 

WORKDIR /patch

# Nun kopiert man aus den vorhergehenden die wichtigen Kompilate
COPY --from=builder /build/entrypoint.sh .	
COPY --from=builder /build/wait-for .
COPY --from=builder /build/frontend/dist/mempool /var/www/mempool
COPY nginx.conf /etc/nginx/
COPY nginx-mempool.conf /etc/nginx/conf.d/

RUN chmod +x /patch/entrypoint.sh
RUN chmod +x /patch/wait-for

RUN chown -R 1000:1000 /patch && chmod -R 755 /patch && \
        chown -R 1000:1000 /var/cache/nginx && \
        chown -R 1000:1000 /var/log/nginx && \
        chown -R 1000:1000 /etc/nginx/nginx.conf && \
        chown -R 1000:1000 /etc/nginx/conf.d && \
        chown -R 1000:1000 /var/www/mempool

RUN touch /var/run/nginx.pid && \
        chown -R 1000:1000 /var/run/nginx.pid

USER 1000

ENTRYPOINT ["/patch/entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
